name: build and push
on: workflow_dispatch

permissions:
  contents: 'read'

env:
  APP_NAME: "postfix"
  TAG: "v1.0.0"

jobs:
  build-and-push-github-package:
    runs-on: ubuntu-latest
    name: build ${{ github.ref_name }}

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Log in to GitHub Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build . --tag ghcr.io/daniyalibrahim/containers/${{ env.APP_NAME }}:${{ env.TAG }} -f Containerfile
        docker push ghcr.io/daniyalibrahim/containers/${{ env.APP_NAME }}:${{ env.TAG }}
